## About datatset
#### The Better Life Index 2024 dataset provides comprehensive indicators across various dimensions of well-being for multiple countries. It encompasses factors such as economic prosperity, housing quality, education, health, safety, and overall life satisfaction.

In [36]:
# Library 

import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt 
import seaborn as sns 
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler, RobustScaler

In [37]:
df = pd.read_csv(r"C:\Users\Maftuna\Desktop\Machine Learning\1 Bo'lim\5 Homework\better-life-index-2024 (1).csv")
df.head()

     Country  ...    Life satisfaction
0  Australia  ...                  7.1
1    Austria  ...                  7.2
2    Belgium  ...                  6.8
3     Canada  ...                  7.0
4      Chile  ...                  6.2

[5 rows x 26 columns]

In [38]:
# Checking the data infprmation
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 26 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   Country                                              38 non-null     object
 1   GDP per capita (USD)                                 38 non-null     int64
 2     Dwellings without basic facilities                 35 non-null     float64
 3     Housing expenditure                                35 non-null     float64
 4     Rooms per person                                   37 non-null     float64
 5     Household net adjusted disposable income           33 non-null     float64
 6     Household net wealth                               29 non-null     float64
 7     Labour market insecurity                           34 non-null     float64
 8     Employment rate                                    38 non-null     int64
 9     Long-term unemployment rate                        37 non-null     float64
 10    Personal earnings                                  35 non-null     float64
 11    Quality of support network                         38 non-null     int64
 12    Educational attainment                             37 non-null     float64
 13    Student skills                                     37 non-null     float64
 14    Years in education                                 37 non-null     float64
 15    Air pollution                                      38 non-null     float64
 16    Water quality                                      38 non-null     int64
 17    Stakeholder engagement for developing regulations  38 non-null     float64
 18    Voter turnout                                      38 non-null     int64
 19    Life expectancy                                    38 non-null     float64
 20    Self-reported health                               38 non-null     int64
 21    Feeling safe walking alone at night                38 non-null     int64
 22    Homicide rate                                      38 non-null     float64
 23    Employees working very long hours                  36 non-null     float64
 24    Time devoted to leisure and personal care          22 non-null     float64
 25    Life satisfaction                                  38 non-null     float64
dtypes: float64(18), int64(7), object(1)
memory usage: 7.8+ KB

##  Missing Values

In [39]:
# Checking the missing values
df.isnull().sum()

Country                                                 0
GDP per capita (USD)                                    0
  Dwellings without basic facilities                    3
  Housing expenditure                                   3
  Rooms per person                                      1
  Household net adjusted disposable income              5
  Household net wealth                                  9
  Labour market insecurity                              4
  Employment rate                                       0
  Long-term unemployment rate                           1
  Personal earnings                                     3
  Quality of support network                            0
  Educational attainment                                1
  Student skills                                        1
  Years in education                                    1
  Air pollution                                         0
  Water quality                                         0
  Stakeholder engagement for developing regulations     0
  Voter turnout                                         0
  Life expectancy                                       0
  Self-reported health                                  0
  Feeling safe walking alone at night                   0
  Homicide rate                                         0
  Employees working very long hours                     2
  Time devoted to leisure and personal care            16
  Life satisfaction                                     0
dtype: int64

In [40]:
# only missing columns

df.columns[df.isna().any()]

Index(['  Dwellings without basic facilities', '  Housing expenditure',
       '  Rooms per person', '  Household net adjusted disposable income',
       '  Household net wealth', '  Labour market insecurity',
       '  Long-term unemployment rate', '  Personal earnings',
       '  Educational attainment', '  Student skills', '  Years in education',
       '  Employees working very long hours',
       '  Time devoted to leisure and personal care'],
      dtype='object')

In [41]:
# Filling the missing values with the mean of the columns
nomerical_columns = df.select_dtypes(include=[np.number]).columns.tolist()
df[nomerical_columns] = df[nomerical_columns].fillna(df[nomerical_columns].mean())

In [42]:
df.isnull().sum()

Country                                                0
GDP per capita (USD)                                   0
  Dwellings without basic facilities                   0
  Housing expenditure                                  0
  Rooms per person                                     0
  Household net adjusted disposable income             0
  Household net wealth                                 0
  Labour market insecurity                             0
  Employment rate                                      0
  Long-term unemployment rate                          0
  Personal earnings                                    0
  Quality of support network                           0
  Educational attainment                               0
  Student skills                                       0
  Years in education                                   0
  Air pollution                                        0
  Water quality                                        0
  Stakeholder engagement for developing regulations    0
  Voter turnout                                        0
  Life expectancy                                      0
  Self-reported health                                 0
  Feeling safe walking alone at night                  0
  Homicide rate                                        0
  Employees working very long hours                    0
  Time devoted to leisure and personal care            0
  Life satisfaction                                    0
dtype: int64

In [43]:
df.head()

     Country  ...    Life satisfaction
0  Australia  ...                  7.1
1    Austria  ...                  7.2
2    Belgium  ...                  6.8
3     Canada  ...                  7.0
4      Chile  ...                  6.2

[5 rows x 26 columns]

##  Encoding

In [44]:
# Category columns

categorical_column = df['Country']

In [45]:
df = pd.get_dummies(df, columns=['Country'], drop_first=True)

In [46]:
df.head()

   GDP per capita (USD)  ...  Country_United States
0                 66589  ...                  False
1                 59225  ...                  False
2                 55536  ...                  False
3                 54866  ...                  False
4                 16616  ...                  False

[5 rows x 62 columns]

In [47]:
# Convert boolean columns to integers
bool_columns = df.select_dtypes(include=['bool']).columns.tolist()
df[bool_columns] = df[bool_columns].astype(int)

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 62 columns):
 #   Column                                               Non-Null Count  Dtype
---  ------                                               --------------  -----
 0   GDP per capita (USD)                                 38 non-null     int64
 1     Dwellings without basic facilities                 38 non-null     float64
 2     Housing expenditure                                38 non-null     float64
 3     Rooms per person                                   38 non-null     float64
 4     Household net adjusted disposable income           38 non-null     float64
 5     Household net wealth                               38 non-null     float64
 6     Labour market insecurity                           38 non-null     float64
 7     Employment rate                                    38 non-null     int64
 8     Long-term unemployment rate                        38 non-null     float64
 9     Personal earnings                                  38 non-null     float64
 10    Quality of support network                         38 non-null     int64
 11    Educational attainment                             38 non-null     float64
 12    Student skills                                     38 non-null     float64
 13    Years in education                                 38 non-null     float64
 14    Air pollution                                      38 non-null     float64
 15    Water quality                                      38 non-null     int64
 16    Stakeholder engagement for developing regulations  38 non-null     float64
 17    Voter turnout                                      38 non-null     int64
 18    Life expectancy                                    38 non-null     float64
 19    Self-reported health                               38 non-null     int64
 20    Feeling safe walking alone at night                38 non-null     int64
 21    Homicide rate                                      38 non-null     float64
 22    Employees working very long hours                  38 non-null     float64
 23    Time devoted to leisure and personal care          38 non-null     float64
 24    Life satisfaction                                  38 non-null     float64
 25  Country_Austria                                      38 non-null     int64
 26  Country_Belgium                                      38 non-null     int64
 27  Country_Canada                                       38 non-null     int64
 28  Country_Chile                                        38 non-null     int64
 29  Country_Colombia                                     38 non-null     int64
 30  Country_Costa Rica                                   38 non-null     int64
 31  Country_Czechia                                      38 non-null     int64
 32  Country_Denmark                                      38 non-null     int64
 33  Country_Estonia                                      38 non-null     int64
 34  Country_Finland                                      38 non-null     int64
 35  Country_France                                       38 non-null     int64
 36  Country_Germany                                      38 non-null     int64
 37  Country_Greece                                       38 non-null     int64
 38  Country_Hungary                                      38 non-null     int64
 39  Country_Iceland                                      38 non-null     int64
 40  Country_Ireland                                      38 non-null     int64
 41  Country_Israel                                       38 non-null     int64
 42  Country_Italy                                        38 non-null     int64
 43  Country_Japan                                        38 non-null     int64
 44  Country_Korea                                        38 non-null     int64
 45  Country_Latvia                                       38 non-null     int64
 46  Country_Lithuania                                    38 non-null     int64
 47  Country_Luxembourg                                   38 non-null     int64
 48  Country_Mexico                                       38 non-null     int64
 49  Country_Netherlands                                  38 non-null     int64
 50  Country_New Zealand                                  38 non-null     int64
 51  Country_Norway                                       38 non-null     int64
 52  Country_Poland                                       38 non-null     int64
 53  Country_Portugal                                     38 non-null     int64
 54  Country_Slovak Republic                              38 non-null     int64
 55  Country_Slovenia                                     38 non-null     int64
 56  Country_Spain                                        38 non-null     int64
 57  Country_Sweden                                       38 non-null     int64
 58  Country_Switzerland                                  38 non-null     int64
 59  Country_Türkiye                                      38 non-null     int64
 60  Country_United Kingdom                               38 non-null     int64
 61  Country_United States                                38 non-null     int64
dtypes: float64(18), int64(44)
memory usage: 18.5 KB

##

## Scaling

In [49]:
df.head(2)

   GDP per capita (USD)  ...  Country_United States
0                 66589  ...                      0
1                 59225  ...                      0

[2 rows x 62 columns]

In [60]:

# Standard Scaling (Z-score normalization)
standard_scaler = StandardScaler()
df_scaled = pd.DataFrame(standard_scaler.fit_transform(df), columns=df.columns)
df_scaled.head(2)

   GDP per capita (USD)  ...  Country_United States
0              0.646065  ...              -0.164399
1              0.388197  ...              -0.164399

[2 rows x 62 columns]

In [64]:
# Min-Max Scaling
min_max_scaler = MinMaxScaler()
df_min_max_scaled = pd.DataFrame(min_max_scaler.fit_transform(df), columns = df.columns)

In [65]:
df_min_max_scaled.head(2)

   GDP per capita (USD)  ...  Country_United States
0               0.47770  ...                    0.0
1               0.41834  ...                    0.0

[2 rows x 62 columns]

In [67]:
# Robust Scaling (handles outliers better)
robust_scaler = RobustScaler()
df_robust_scaled = pd.DataFrame(robust_scaler.fit_transform(df), columns = df.columns)

In [68]:
df_robust_scaled.head(2)

   GDP per capita (USD)  ...  Country_United States
0              0.711413  ...                    0.0
1              0.484814  ...                    0.0

[2 rows x 62 columns]